language: android

# enables container-based infrastructure
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    
    # Support library
    - extra-android-support
    - extra-android-m2repository
